### ISSUE TITLE
`ncat` can do the same thing

### ISSUE THREAD

**Issue by jtarchie** [jasonkeene/tcp-to-stdout#1]
For reference `ncat`, that comes with `nmap` can do this, too.

For example,

```
# listen on port 8080 for multiple connections and keep them alive
$ ncat -k -l -p 8080
```

**Comment by jtarchie** [comment]
For MAC support, you need to `brew install nmap`.

**Comment by jasonkeene** [comment]
Fixed this, see: https://github.com/jasonkeene/tcp-to-stdout/commit/63296adfd8c50a0cc2073a5af07dca2cd67190c5
